//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaladuradeJabones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProveedores
    {
        public short ProveedorId { get; set; }
        public string Lista { get; set; }
        public short Coste { get; set; }
    }
}
